### PR TITLE
Fix crash on non-existant user ID

### LINKED ISSUE #238: AttributeError: 'NoneType' object has no attribute 'password'
Happens if I delete the DB file. Works if I leave it alone for a few.
Nothing with variables, this is all something with Flask-User
Full Traceback:
```
Traceback (most recent call last):
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ec2-user/environment/AmusedGrape/ask/server.py", line 128, in home_page
    return render_template('index.html')
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/templating.py", line 133, in render_template
    ctx.app.update_template_context(context)
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask/app.py", line 792, in update_template_context
    context.update(func())
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask_login/utils.py", line 368, in _user_context_processor
    return dict(current_user=_get_user())
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask_login/utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask_login/login_manager.py", line 359, in _load_user
    return self.reload_user()
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask_login/login_manager.py", line 321, in reload_user
    user = self.user_callback(user_id)
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask_user/user_manager.py", line 130, in load_user_by_user_token
    user = self.db_manager.UserClass.get_user_by_token(user_token)
  File "/home/ec2-user/environment/AmusedGrape/ask/flask/lib/python3.6/dist-packages/flask_user/user_mixin.py", line 52, in get_user_by_token
    user_password = '' if user_manager.USER_ENABLE_AUTH0 else user.password[-8:]
AttributeError: 'NoneType' object has no attribute 'password'
```

### PR DESCRIPTION
**Pull request by rubenwardy**
Fixes #238

If a user is deleted then any logged-in sessions will cause an exception due to a NoneType user

### CODE REVIEW

**Comment by rubenwardy** [comment]
on a semi-related note, this function would read a lot better like this:

```py
# Verifies a token and decrypts a User ID and parts of a User password hash
user_manager = current_app.user_manager
data_items = user_manager.verify_token(token, expiration_in_seconds)
if not data_items:
	return None

# Load user by User ID
user_id = data_items[0]
password_ends_with = data_items[1]
user = user_manager.db_manager.get_user_by_id(user_id)
if not user:
	return None

# Make sure that last 8 characters of user password matches
user_password = '' if user_manager.USER_ENABLE_AUTH0 else user.password[-8:]

return user if user_password==password_ends_with else None
```

you remove the unnecessary `token_is_valid` variable, and have a simpler control flow (ie: if data_items is None, then it always returns None)

**Comment by divad1196** [comment]
Based on @rubenwardy reply, here is the fix i did in my code
`
from flask_user import UserMixin

@classmethod
def get_user_by_token(cls, token, expiration_in_seconds=None):
    # This function works in tandem with UserMixin.get_id()
    # Token signatures and timestamps are verified.
    # user_id and password_ends_with are decrypted.

    # Verifies a token and decrypts a User ID and parts of a User password hash
    user_manager = current_app.user_manager
    data_items = user_manager.verify_token(token, expiration_in_seconds)

    # Verify password_ends_with
    if data_items:

        # Load user by User ID
        user_id = data_items[0]
        password_ends_with = data_items[1]
        user = user_manager.db_manager.get_user_by_id(user_id)
        if not user:
	        return None
        user_password = '' if user_manager.USER_ENABLE_AUTH0 else user.password[-8:]

        # Make sure that last 8 characters of user password matches
        token_is_valid = user and user_password==password_ends_with
        return user if token_is_valid else None

    return None
UserMixin.get_user_by_token = get_user_by_token
`

It can be called anywhere, but i recommand to keep it before the first use of UserMixin.

I also reorganised the conditions

**Comment by jaredthecoder** [comment]
Is there anything we can do to get this merged?

**Comment by rubenwardy** [comment]
@lingthio would be nice to have a review

**Pull request closed without merging**
