### PR TITLE
Tell a user if the email is not present in database

### PR DESCRIPTION
**Pull request by lanart**
Tell a user if the email that user provide because he forgot a password is not present in database.

### CODE REVIEW

**Comment by lingthio** [comment]
Hi @lanart : I understand your desire to show error messages of non-displayed form fields, but I don't like  the solution you're proposing because it creates additional (and perhaps unnecessary) behavioural differences between development systems and production systems.

Can you give me more info on your use case, so we can come up with a different approach? Why are you (or where is Flask-User) hiding a form field from display? Is it possible to remove this field from the Form object (vs removing it from its HTML)?

**Comment by lanart** [comment]
Hi Ling,

I had a hard time implementing Flask-User in my application. No doubt, it
was my errors, but it was difficult to figure out what was wrong because of
too many factors.

I was not working on my application for a few weeks and when I was back I
used the wrong email to login and then requested to send a password via
email. When nothing arrived I thought it was SMTP problem. I was stuck on a
problem for a few hours trying to debug SMTP problems, but nothing happens
until I understand that it was a wrong email. It's nice to know what's
happening especially when you are learning a new tool.

The same thing with validation error. I've used the wrong validation form.
This is my fault because I was not familiar with Flask-User. There were
validation constraints for the fields that were not present on the form. It
is a problem that should be resolved on development platform and is useless
in production.

I think this changes can just make a life for a newcomer developer a little
bit easier.

Cheers

Andrei

2015-08-03 18:29 GMT+02:00 Ling Thio <notifications@github.com>:

> Hi @lanart <https://github.com/lanart> : I understand your desire to show
> error messages of non-displayed form fields, but I don't like the solution
> you're proposing because it creates additional (and perhaps unnecessary)
> behavioural differences between development systems and production systems.
>
> Can you give me more info on your use case, so we can come up with a
> different approach? Why are you (or where is Flask-User) hiding a form
> field from display? Is it possible to remove this field from the Form
> object (vs removing it from its HTML)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lingthio/Flask-User/pull/78#issuecomment-127310522>.
>



-- 
Didotech Srl

Via T.Aspetti, 248
35133 Padova (PD)

Tel 049 8592286
Cell.: 347-2426694
www.didotech.com

**Comment by lingthio** [comment]
As I said before: I understand and I want to help you, but I need some specifics:
- which form contains fields that are NOT exposed in its corresponding html?
- which field?
Or in another way: Which validation error messages are not being shown and in which form?

Also: v0.6.5 now explicitly shows a 'email not found' validation error when USER_ENABLE_REGISTER is true or USER_SHOW_USERNAME_EMAIL_NOT_FOUND is true.

**Comment by lanart** [comment]
I tried to use flask-user as a blueprint in my application. So I removed a
blueprint that uses flask-login and I take pieces from your example
application. At the end I have a registration form that requires username,
email and password and validation form class that requires first_name and
last_name. When I was trying to register I see no errors, because errors
are shown on fields that are present in the form. This is right approach
for the working application, but it was difficult to figure out what was
wrong until I started to debug flask-user code.

I was not sure that it can work, because the possibility to use Flask-user
as a blueprint is not mentioned in the documentation. Now I can confirm
that it works.



2015-08-05 20:31 GMT+02:00 Ling Thio <notifications@github.com>:

> As I said before: I understand and I want to help you, but I need some
> specifics:
>
>    - which form contains fields that are NOT exposed in its corresponding
>    html?
>    - which field? Or in another way: Which validation error messages are
>    not being shown and in which form?
>
> Also: v0.6.5 now explicitly shows a 'email not found' validation error
> when USER_ENABLE_REGISTER is true or USER_SHOW_USERNAME_EMAIL_NOT_FOUND is
> true.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lingthio/Flask-User/pull/78#issuecomment-128101005>.
>



-- 
Didotech Srl

Via T.Aspetti, 248
35133 Padova (PD)

Tel 049 8592286
Cell.: 347-2426694
www.didotech.com

**Comment by lingthio** [comment]
'Email does not exist' error messages have been added.

I do not plan to implement showing field error messages that have been removed from the form. I recommend deriving your own form without this field, if you want to omit a field.

**Pull request closed without merging**
