### PR TITLE
Added support for manual user activation

### PR DESCRIPTION
**Pull request by langep**

### CODE REVIEW

**Comment by c0ffee** [comment]
is there any chance, that this will be merged soon? defiantly a good feature!

**Comment by langep** [comment]
@c0ffee Do you know if similar functionality is supported by now?

**Comment by and-semakin** [comment]
Hi @langep! Thank you for your contribution! Could you please update/rebase your branch over current master?

**Comment by langep** [comment]
Thanks @and-semakin for the reminder. I had completely forgotten about this. I should be able to get to this over the next few days.

**Comment by langep** [comment]
I took a look at the recent code and it seems that the code base changed quite a bit in the past 3 years. I don't have the time to investigate how to implement this feature nor do I know if this is still relevant. I am closing the PR.

**Comment by and-semakin** [comment]
Sorry to hear that. If you find spare time, feel free to reopen this or create new PR :)

**Comment by langep** [comment]
I think starting a new PR seems more reasonable. When I had a quick look, I saw some new features and for my use case, invitation with token would probably have worked, too. I will give it another look when I have a few hours of spare time.

**Pull request closed without merging**
